# Generated by Django 4.1.7 on 2023-03-31 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectData",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("cloths", models.IntegerField()),
                ("underwear", models.IntegerField()),
                ("sportswear", models.IntegerField()),
                ("accessories", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nbr_children", models.IntegerField()),
                ("career", models.CharField(max_length=100)),
                ("shopping_price", models.IntegerField()),
                (
                    "collect_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataAnalyse.collectdata",
                    ),
                ),
            ],
        ),
    ]
