# Generated by Django 4.1.7 on 2023-03-31 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("DataAnalyse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="collect_data",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DataAnalyse.collectdata",
            ),
        ),
    ]
